package CookBook.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int CookBook = 0;
  public static final int InputField = 1;
  public static final int InputFieldRefrence = 2;
  public static final int OutputField = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x2e1e7e62debb4c4bL, 0xbcca55fb2d10f07aL);
    builder.put(0x339621b95d3993aaL, CookBook);
    builder.put(0x339621b95d3adab5L, InputField);
    builder.put(0x6a00c499306c9403L, InputFieldRefrence);
    builder.put(0x339621b95d3cabbfL, OutputField);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
